name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          AUTHOR_NAME: Kais Abiyyi
          AUTHOR_EMAIL: kaisabiyyi2@gmail.com
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: KaisAbiyyi/KaisAbiyyi
